name: Semgrep Autofix

on:
  pull_request:

jobs:
  semgrep_autofix:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # allows pushing back to repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep Autofix
        run: |
          semgrep --config=.semgrep.yml --autofix --json > semgrep-output.json || true
          cat semgrep-output.json
      - name: Set branch name
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          BASE_BRANCH="${{ github.event.pull_request.head.ref }}"
          FIX_BRANCH="semgrep/autofix-${BASE_BRANCH}-${TIMESTAMP}"
          echo "Base branch: $BASE_BRANCH"
          echo "fix branch: $FIX_BRANCH"

      - name: Commit & Push Fixes
        if: success()
        run: |
          git config user.name "semgrep-bot"
          git config user.email "semgrep@bot.dev"

          if ! git diff --quiet; then
            git fetch origin "$BASE_BRANCH"
            git checkout -b "$FIX_BRANCH" "origin/$BASE_BRANCH"
            git add .
            git commit -m "chore: semgrep autofix for ${HEAD_BRANCH} at ${TIMESTAMP}"
            git push origin "$FIX_BRANCH"
            echo "fix_branch=$FIX_BRANCH" >> "$GITHUB_OUTPUT"
            echo "base_branch=$BASE_BRANCH" >> "$GITHUB_OUTPUT"
          else
            echo "No changes to commit."
          fi

        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Create PR to Same Branch
        if: success()
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "chore: semgrep autofix"
          title: "Semgrep Autofix for $BASE_BRANCH"
          body: |
            Automatic semgrep autofixes applied. Please review & merge.
          branch: $FIX_BRANCH
          base: $BASE_BRANCH
