name: Semgrep Autofix

on:
  schedule:
    - cron: '0 1 * * *' # Daily 1 AM UTC run
  workflow_dispatch:
  push:
    branches: [main] # Adjust to your dev branch
  pull_request:

jobs:
  semgrep_autofix:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # allows pushing back to repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep Autofix
        run: |
          semgrep --config=.semgrep.yml --autofix --json > semgrep-output.json || true
          cat semgrep-output.json

      - name: Run Tests (mock)
        run: |
          echo "⚠️ Replace with your actual test command"
          echo "Running tests..."
          # npm test OR go test ./... OR pytest, etc.

      - name: Commit & Push Fixes
        if: success()
        run: |
          git config user.name "semgrep-bot"
          git config user.email "semgrep@bot.dev"

          if ! git diff --quiet; then
            git add .
            git commit -m "chore: semgrep autofix"
            git push origin HEAD
          else
            echo "No changes to commit."
          fi