name: Semgrep Autofix

on:
  pull_request:

jobs:
  semgrep_autofix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep Autofix
        run: |
          semgrep --config=.semgrep.yml --autofix --json > semgrep-output.json || true
          cat semgrep-output.json

      - name: Commit & Push Fixes
        id: commit_and_push
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE_BRANCH="${{ github.event.pull_request.head.ref }}"
          else
            BASE_BRANCH="${{ github.ref_name }}"
          fi

          FIX_BRANCH="semgrep/autofix-${BASE_BRANCH}-${TIMESTAMP}"

          git config user.name "semgrep-bot"
          git config user.email "semgrep@bot.dev"

          if ! git diff --quiet; then
            git fetch origin "$BASE_BRANCH"
            git checkout -b "$FIX_BRANCH" "origin/$BASE_BRANCH"
            git add .
            git commit -m "chore: semgrep autofix for ${BASE_BRANCH} at ${TIMESTAMP}"
            git push origin "$FIX_BRANCH"
            echo "branch_name=$FIX_BRANCH" >> "$GITHUB_OUTPUT"
            echo "base_branch=$BASE_BRANCH" >> "$GITHUB_OUTPUT"
          else
            echo "No changes to commit."
          fi

        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Create PR to Same Branch
        if: success()
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "chore: semgrep autofix"
          title: "Semgrep Autofix for ${{ steps.commit_and_push.outputs.base_branch }}"
          body: |
            Automatic semgrep autofixes applied. Please review & merge.
          branch: ${{ steps.commit_and_push.outputs.branch_name }}
          base: ${{ steps.commit_and_push.outputs.base_branch }}
